name: nidhi_expense_tracker
description: A Flutter project to track daily expenses with categories and summaries.
publish_to: 'none' # Uncomment this line if you are publishing the package to pub.dev.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  http: ^0.14.0

  # For responsive layouts
  flutter_screenutil: ^5.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  hive_generator: ^1.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/ # If you have any images you want to add to the app
    - assets/fonts/  # If you want to include custom fonts
